# Sesión 3.2: Factorización LU - Guía de Resolución Manual
**Asignatura:** Métodos Numéricos
**Docente:** Ricardo Largaespada
**Objetivo:** Comprender y aplicar manualmente la descomposición de una matriz $A$ en sus componentes triangular inferior ($L$) y superior ($U$).

---
## 1. El Problema
Dada una matriz $A$, buscamos $A = LU$ tal que:
$$L = \begin{pmatrix} 1 & 0 & 0 \\ m_{21} & 1 & 0 \\ m_{31} & m_{32} & 1 \end{pmatrix}, \quad U = \begin{pmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{pmatrix}$$

Donde los multiplicadores $m_{ij}$ son los valores utilizados para eliminar elementos durante la eliminación gaussiana.

## 2. Ejercicio para realizar en clase (Manual)
Consideremos la matriz:
$$A = \begin{pmatrix} 4 & 3 & -1 \\ -2 & -4.5 & 7 \\ 5 & 3 & 2 \end{pmatrix}$$

### Paso 1: Eliminar elementos bajo $a_{11}$ (Columna 1)
* **Multiplicador $m_{21}$:** $\frac{-2}{4} = -0.5$
* **Multiplicador $m_{31}$:** $\frac{5}{4} = 1.25$

**Operaciones:**
* $F_2 \leftarrow F_2 - (-0.5)F_1$
* $F_3 \leftarrow F_3 - (1.25)F_1$

### Paso 2: Eliminar elementos bajo $a'_{22}$ (Columna 2)
* Tras el Paso 1, la matriz parcial es $A'$. Calculamos el nuevo multiplicador $m_{32}$.
* **Multiplicador $m_{32}$:** $\frac{a'_{32}}{a'_{22}}$

---
## 3. Verificación Computacional
Utiliza el siguiente bloque de código para verificar tus resultados manuales.

In [1]:
import numpy as np

def factorizacion_lu_paso_a_paso(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy().astype(float)
    
    print("--- Proceso de Factorización ---")
    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] -= factor * U[i, i:]
            print(f"Multiplicador m[{j+1},{i+1}] = {factor}")
            
    return L, U

# Definir la matriz A
A = np.array([[4, 3, -1], 
              [-2, -4.5, 7], 
              [5, 3, 2]], dtype=float)

L, U = factorizacion_lu_paso_a_paso(A)

print("\nMatriz L (Inferior):")
print(L)
print("\nMatriz U (Superior):")
print(U)
print("\nVerificación L * U:")
print(np.dot(L, U))

--- Proceso de Factorización ---
Multiplicador m[2,1] = -0.5
Multiplicador m[3,1] = 1.25
Multiplicador m[3,2] = 0.25

Matriz L (Inferior):
[[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 1.25  0.25  1.  ]]

Matriz U (Superior):
[[ 4.     3.    -1.   ]
 [ 0.    -3.     6.5  ]
 [ 0.     0.     1.625]]

Verificación L * U:
[[ 4.   3.  -1. ]
 [-2.  -4.5  7. ]
 [ 5.   3.   2. ]]


In [2]:
import numpy as np

def factorizacion_lu_paso_a_paso(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy().astype(float)
    
    print("--- Proceso de Factorización ---")
    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] -= factor * U[i, i:]
            print(f"Multiplicador m[{j+1},{i+1}] = {factor}")
            
    return L, U

# Definir la matriz A
A = np.array([[8, 2, 1], 
              [3, 7, 2], 
              [2, 3, 9]], dtype=float)

L, U = factorizacion_lu_paso_a_paso(A)

print("\nMatriz L (Inferior):")
print(L)
print("\nMatriz U (Superior):")
print(U)
print("\nVerificación L * U:")
print(np.dot(L, U))

--- Proceso de Factorización ---
Multiplicador m[2,1] = 0.375
Multiplicador m[3,1] = 0.25
Multiplicador m[3,2] = 0.4

Matriz L (Inferior):
[[1.    0.    0.   ]
 [0.375 1.    0.   ]
 [0.25  0.4   1.   ]]

Matriz U (Superior):
[[8.    2.    1.   ]
 [0.    6.25  1.625]
 [0.    0.    8.1  ]]

Verificación L * U:
[[8. 2. 1.]
 [3. 7. 2.]
 [2. 3. 9.]]


In [5]:
import linearalgebra as la
print(la.det(A))

ModuleNotFoundError: No module named 'linearalgebra'